//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
// 
#pragma warning disable 1591

namespace CMSSolutions.Websites.VipHDBankCardServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DepositOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback comfirmOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::CMSSolutions.Websites.Properties.Settings.Default.CMSSolutions_Websites_VipHDBankCardServices_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DepositCompletedEventHandler DepositCompleted;
        
        /// <remarks/>
        public event getStatusCompletedEventHandler getStatusCompleted;
        
        /// <remarks/>
        public event comfirmCompletedEventHandler comfirmCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Deposit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public reponse Deposit(string merchantid, string stan, string termtxndatetime, string txnAmount, string fee, string userName, string IssuerID, string tranID, string bankID, string mac, string respUrl) {
            object[] results = this.Invoke("Deposit", new object[] {
                        merchantid,
                        stan,
                        termtxndatetime,
                        txnAmount,
                        fee,
                        userName,
                        IssuerID,
                        tranID,
                        bankID,
                        mac,
                        respUrl});
            return ((reponse)(results[0]));
        }
        
        /// <remarks/>
        public void DepositAsync(string merchantid, string stan, string termtxndatetime, string txnAmount, string fee, string userName, string IssuerID, string tranID, string bankID, string mac, string respUrl) {
            this.DepositAsync(merchantid, stan, termtxndatetime, txnAmount, fee, userName, IssuerID, tranID, bankID, mac, respUrl, null);
        }
        
        /// <remarks/>
        public void DepositAsync(string merchantid, string stan, string termtxndatetime, string txnAmount, string fee, string userName, string IssuerID, string tranID, string bankID, string mac, string respUrl, object userState) {
            if ((this.DepositOperationCompleted == null)) {
                this.DepositOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDepositOperationCompleted);
            }
            this.InvokeAsync("Deposit", new object[] {
                        merchantid,
                        stan,
                        termtxndatetime,
                        txnAmount,
                        fee,
                        userName,
                        IssuerID,
                        tranID,
                        bankID,
                        mac,
                        respUrl}, this.DepositOperationCompleted, userState);
        }
        
        private void OnDepositOperationCompleted(object arg) {
            if ((this.DepositCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DepositCompleted(this, new DepositCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public reponse getStatus(string tranid, string merchantcode, string mackey) {
            object[] results = this.Invoke("getStatus", new object[] {
                        tranid,
                        merchantcode,
                        mackey});
            return ((reponse)(results[0]));
        }
        
        /// <remarks/>
        public void getStatusAsync(string tranid, string merchantcode, string mackey) {
            this.getStatusAsync(tranid, merchantcode, mackey, null);
        }
        
        /// <remarks/>
        public void getStatusAsync(string tranid, string merchantcode, string mackey, object userState) {
            if ((this.getStatusOperationCompleted == null)) {
                this.getStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStatusOperationCompleted);
            }
            this.InvokeAsync("getStatus", new object[] {
                        tranid,
                        merchantcode,
                        mackey}, this.getStatusOperationCompleted, userState);
        }
        
        private void OngetStatusOperationCompleted(object arg) {
            if ((this.getStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStatusCompleted(this, new getStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/comfirm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public reponse comfirm(string merchantcode, string tranid, string txnAmount, string confirmCode, string mackey) {
            object[] results = this.Invoke("comfirm", new object[] {
                        merchantcode,
                        tranid,
                        txnAmount,
                        confirmCode,
                        mackey});
            return ((reponse)(results[0]));
        }
        
        /// <remarks/>
        public void comfirmAsync(string merchantcode, string tranid, string txnAmount, string confirmCode, string mackey) {
            this.comfirmAsync(merchantcode, tranid, txnAmount, confirmCode, mackey, null);
        }
        
        /// <remarks/>
        public void comfirmAsync(string merchantcode, string tranid, string txnAmount, string confirmCode, string mackey, object userState) {
            if ((this.comfirmOperationCompleted == null)) {
                this.comfirmOperationCompleted = new System.Threading.SendOrPostCallback(this.OncomfirmOperationCompleted);
            }
            this.InvokeAsync("comfirm", new object[] {
                        merchantcode,
                        tranid,
                        txnAmount,
                        confirmCode,
                        mackey}, this.comfirmOperationCompleted, userState);
        }
        
        private void OncomfirmOperationCompleted(object arg) {
            if ((this.comfirmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.comfirmCompleted(this, new comfirmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class reponse {
        
        private string responsecodeField;
        
        private string tranidField;
        
        private string descriptionvnField;
        
        private string descriptionenField;
        
        private string statusField;
        
        private string urlField;
        
        private string macField;
        
        /// <remarks/>
        public string responsecode {
            get {
                return this.responsecodeField;
            }
            set {
                this.responsecodeField = value;
            }
        }
        
        /// <remarks/>
        public string tranid {
            get {
                return this.tranidField;
            }
            set {
                this.tranidField = value;
            }
        }
        
        /// <remarks/>
        public string descriptionvn {
            get {
                return this.descriptionvnField;
            }
            set {
                this.descriptionvnField = value;
            }
        }
        
        /// <remarks/>
        public string descriptionen {
            get {
                return this.descriptionenField;
            }
            set {
                this.descriptionenField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string mac {
            get {
                return this.macField;
            }
            set {
                this.macField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DepositCompletedEventHandler(object sender, DepositCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DepositCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DepositCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public reponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((reponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getStatusCompletedEventHandler(object sender, getStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public reponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((reponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void comfirmCompletedEventHandler(object sender, comfirmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class comfirmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal comfirmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public reponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((reponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591